GO

/****** Object: SqlProcedure [dbo].[FI_SP_IncClienteV2] Script Date: 11/9/2019 4:14:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC FI_SP_IncClienteBeneficiarios
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @NACIONALIDADE VARCHAR (50) ,
    @CEP           VARCHAR (9)  ,
    @ESTADO        VARCHAR (2)  ,
    @CIDADE        VARCHAR (50) ,
    @LOGRADOURO    VARCHAR (500),
    @EMAIL         VARCHAR (2079),
    @TELEFONE      VARCHAR (15),
	@CPF		   VARCHAR (15),
	@BENEFICIARIOS BeneficiariosType READONLY

AS
BEGIN
	DECLARE @ID_CLIENTE INT = NULL

	INSERT INTO CLIENTES (NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF) 
	VALUES (@NOME, @SOBRENOME,@NACIONALIDADE,@CEP,@ESTADO,@CIDADE,@LOGRADOURO,@EMAIL,@TELEFONE, @CPF)

	SET @ID_CLIENTE = (SELECT @@IDENTITY)

	IF EXISTS(SELECT TOP(1) * FROM @BENEFICIARIOS)
	BEGIN
		INSERT INTO BENEFICIARIOS
		SELECT CPF, NOME, @ID_CLIENTE AS 'IDCLIENTE' FROM @BENEFICIARIOS
	END
	--SELECT SCOPE_IDENTITY()
	SELECT @ID_CLIENTE
END
